### ISSUE TITLE
Thunderbirds profile folder gets deleted when purging Betterbird

### ISSUE THREAD

**Issue by 1u** [flathub/eu.betterbird.Betterbird#192] opened 2024-11-13 17:59 UTC
## Steps to reproduce

- Installing Betterbird on Linux with FlatPak
- Importing existing profile from Thunderbird by pointing to the  `foo.profile` directory 
  (menu -> tools -> import -> import from another Thunderbird-installation -> choose my profile folder in `~/.thunderbird/` )
  (looks like it copies the folder to somewhere? (-> size of the folder (in my case 10 GB) is used on drive additionally..)
- Removing Betterbird again with `flatpak uninstall --delete-data betterbird`

## Bug
Problem: this results in the original profile folder is emptied  (happy i did a backup just before starting...)

## Further information

- Betterbird states you can switch between Thunderbird and Betterbird in https://www.betterbird.eu/support/
- Not possible to delete `$ sudo rm -rf /run/user/1000/doc/83bf3f54/*` instead of purging the installation

https://github.com/Betterbird/thunderbird-patches/issues/367

**Comment by mfschumann** [comment] 2024-11-14 18:52
Can you confirm that you did not change any permissions for the flatpak by running `flatpak override` or using flatseal?

By default, flatpak Betterbird stores the profiles in `~/.var/app/eu.betterbird.Betterbird/.thunderbird`, i.e. separately from both the non-flatpak installation of Betterbird and any Thunderbird installation. I would expect this behavior:
1. The profile importer either copies or moves the profile from `~/.thunderbird` to `~/.var/app/eu.betterbird.Betterbird/.thunderbird`. 
2. Once you remove the flatpak with the `--delete-data` flag, the Betterbird version of the profiles in `~/.var/app/eu.betterbird.Betterbird/.thunderbird` is purged. 

Meaning that if the profile importer moved the profile in step 1 (instead of copying it), it is gone in the end. 

Can you check if the profile in `~/.thunderbird` is still there after step 1?

**Comment by 1u** [comment] 2024-11-14 20:31
Yes, the original is still there.
And confirming, the one used by Betterbird is copied to and used from `~/.var/app/eu.betterbird.Betterbird/.thunderbird`

I don't have the time and nerves to further investigate in this or reproduce it again. As written, I tried to remove Betterbird by deleting the run/user/1000/doc. Maybe deleting happened differently than while `...--delete-data betterbird`.

If there are simple question I can answer them.
Thanks for your understanding

& Thanks for your support and sorry for wasting your time in case I was wrong.

**Comment by mfschumann** [comment] 2024-11-18 20:26
I have unsuccessfully tried to reproduce the issue with Betterbird 128.4.3 from [flathub beta](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111):
1. I have created a fresh linux user and set up a Thunderbird profile in `~/.thunderbird`.
2. I have installed Betterbird and tried to import the profile from `~/.thunderbird` using the Import Wizard in the Tools menu.
3. As expected the path `~/.thunderbird` is converted to a path in `/run/user/<id>/doc` since the home folder is not directly accessible from the flatpak sandbox. Instead the folder is selectively made accessible by flatpak using a so-called [portal](https://docs.flatpak.org/en/latest/sandbox-permissions.html). Or it *should* be, as that does not seem to work for the Thunderbird profile:
![Bildschirmfoto vom 2024-11-18 21-05-29](https://github.com/user-attachments/assets/e7a809ac-1e10-41c6-bdd7-34eaec7eaa9a)

4. Starting Thunderbird again, the profile is loaded fine. 
5. I forgot to test running `flatpak uninstall --delete-data eu.betterbird.Betterbird` to complete the test, but I don't see why that should harm the `~/.thunderbird` directory.

Please let me know if my test matches what you did and what exactly you tried to do to the `/run/user/1000/doc/83bf3f54` folder and when (you are not supposed to delete these folders).

**Comment by mfschumann** [comment] 2024-11-18 20:31
I've just re-read your reply.

> As written, I tried to remove Betterbird by deleting the run/user/1000/doc

I think that is the origin of the problem: Flatpak may have made `~/.thunderbird` accessible there and you have deleted the folder.

I am closing the issue for now since I tend to believe this is a user error. Feel free to reopen if you can give instructions to reproduce the issue.

**Closed by mfschumann** 2024-11-18 20:31 UTC
