### ISSUE TITLE
Customize tray icon

### ISSUE THREAD

**Issue by bmp** [flathub/eu.betterbird.Betterbird#158] opened 2024-06-07 12:24 UTC
Hello,

I have the following two icons I am using:
![default](https://github.com/flathub/eu.betterbird.Betterbird/assets/1095177/43553ea0-c383-4dc7-845c-8bb5a09ae4a8)
![newmail](https://github.com/flathub/eu.betterbird.Betterbird/assets/1095177/8b997d1f-fd24-461d-8cfd-a154cf3a6568)

I am able to change icons based on the https://www.betterbird.eu/expert-tips/index.html when I use the application from source.

How can I customize the tray icon when I use the flatpak?

**Comment by mfschumann** [comment] 2024-06-07 14:43
For the flatpak version of Betterbird to pick up the icons, they 

- must reside in the subfolder `icons/hicolor/scalable/status` below any of the directories in `$XDG_DATA_DIRS` ([spec](https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s03.html)). 
- must be named `eu.betterbird.Betterbird-default.svg` and `eu.betterbird.Betterbird-newmail.svg`, respectively.

On my computer, `$XDG_DATA_DIRS` starts with two folders where flatpak puts the icons of the installed apps (`.../flatpak/exports/share`). I would not recommend messing around in these folders since eventually a flatpak update will restore the original state. Instead, I would prepend a custom folder to `$XDG_DATA_DIRS` and put the custom icons in there according to the two requirements above (correct subfolder, correct name).

**Comment by mfschumann** [comment] 2024-06-07 16:17
You could try restarting your session again after putting the icons into the correct location. Maybe the icons need to be present when the session starts?

**Comment by mfschumann** [comment] 2024-06-07 16:53
Hm, that is strange. I will try to reproduce and debug the issue on my machine, but that is going to take a while.

**Comment by mfschumann** [comment] 2024-07-02 19:35
On my fedora Silverblue machine with GNOME, I was able to customize the tray icon like this:
1. Create folder `~/.local/share/icons/hicolor/scalable/status`
2. Place `eu.betterbird.Betterbird-default.svg` and `eu.betterbird.Betterbird-newmail.svg` in this folder
3. Reboot

After that Betterbird showed the custom tray icon.

Note that I did not even have to add anything to `$XDG_DATA_DIRS` because `$XDG_DATA_HOME` is checked first for matching icons. On my machine the latter is unset so it defaults to `$HOME/.local/share` ([spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)). 

The only obvious differences between my test and yours are 

- GNOME vs. KDE 
- a different directory where the icons are placed

Could you check if placing the icons in `~/.local/share/icons/hicolor/scalable/status` and undoing your changes to `$XDG_DATA_DIRS` works for you too? 

Btw, thanks for posting the icons. That monochrome style matches my desktop quite nicely :-)

**Comment by mfschumann** [comment] 2024-07-03 10:23
Note it should be `~/.local/share/icons`, you seem to be missing the `share` part.

**Comment by mfschumann** [comment] 2024-07-03 20:20
I've spun up a Tumbleweed VM and tested the approach that I described in https://github.com/flathub/eu.betterbird.Betterbird/issues/158#issuecomment-2204200334, and it worked:

![image](https://github.com/flathub/eu.betterbird.Betterbird/assets/9102962/c6e26617-3393-4902-9b7a-a984b557296b)

So it's not a KDE vs. GNOME issue, but seems specific to your setup. Can you try if the approach works under a freshly created user account?

**Comment by mfschumann** [comment] 2024-07-09 04:26
I've added instructions for icon customization to the FAQ of this repo in #162. 

I am going to close this issue for now since it does not seem to be an issue with the flatpak package itself. Feel free to leave a comment on the results of the user account test.

**Closed by mfschumann** 2024-07-09 04:26 UTC
